cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'zsh'
brew 'antibody'
brew 'readline'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'rbenv'
brew 'tldr'
brew 'coreutils'
brew 'robotsandpencils/made/xcodes'
brew 'aria2'

cask 'visual-studio-code'
cask 'firefox'
cask 'iterm2'
cask 'spotify'
cask '1password'
cask 'insomnia'
cask 'docker'
cask 'keepingyouawake'

tap 'homebrew/cask-fonts'
cask 'font-fira-mono'
cask 'font-fira-code'
cask 'font-victor-mono'
cask 'font-cascadia-code'