cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'zsh'
brew 'antigen'
brew 'readline'
brew 'node'
brew 'nvm'
brew 'python'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'rbenv'
brew 'cowsay'
brew 'fortune'
brew 'lolcat'
brew 'carthage'

tap 'caskroom/cask'
cask 'visual-studio-code'
cask 'opera'
cask 'iterm2'
cask 'spotify'
cask 'dropbox'
cask '1password'
cask 'docker'
cask 'keepingyouawake'

tap 'caskroom/fonts'
cask 'font-fira-mono'
cask 'font-fira-mono-for-powerline'
cask 'font-fira-code'
cask 'font-monofur'
cask 'font-hack'
