set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/plugins')

Plugin 'connorholyday/vim-snazzy'
Plugin 'itchyny/lightline.vim'


" All of your Plugins must be added before the following line
call vundle#end()           " required
filetype plugin indent on   " required

let g:SnazzyTransparent = 1
colorscheme snazzy

let g:lightline = {
\ 'colorscheme': 'snazzy',
\ }

syntax enable           " enable syntax processing

set tabstop=4           " number of visual spaces per TAB
set softtabstop=4       " number of spaces in tab when editing
set expandtab           " tabs are spaces

set number              " show line numbers
set showcmd             " show command in bottom bar
filetype indent on      " load filetype-specific indent files
set wildmenu            " visual autocomplete for command menu

