call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'

Plug 'connorholyday/vim-snazzy'

call plug#end()

filetype plugin indent on

let g:SnazzyTransparent = 1
colorscheme snazzy

let g:lightline = {
\ 'colorscheme': 'snazzy',
\ }

syntax enable           " enable syntax processing

set tabstop=4           " number of visual spaces per TAB
set softtabstop=4       " number of spaces in tab when editing
set expandtab           " tabs are spaces

set number              " show line numbers
set showcmd             " show command in bottom bar
filetype indent on      " load filetype-specific indent files
set wildmenu            " visual autocomplete for command menu

set laststatus=2
set noshowmode
